### DISCUSSION TITLE
How to get apk package

### DISCUSSION THREAD

**Discussion by jsprog** [rust-mobile/cargo-apk#61] [Q&A] [answered]
I already run a simple [slint](https://slint.dev/) app on my phone using this command
```
RUSTFLAGS="-Z location-detail=none" \
    cargo +nightly apk run --lib --release \
    --target aarch64-linux-android
```

Of course, I added this section to `Cargo.toml` after generating the keystore file with `keytool`
```toml
[package.metadata.android.signing.release]
path = "my-release-key.keystore"
keystore_password = "password"
```

Question: **How can I get the apk file?**
